# Generated by Django 5.2.4 on 2025-07-22 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-date'], 'verbose_name': 'ข้อมูลนักศึกษา', 'verbose_name_plural': 'ข้อมูลนักศึกษาทั้งหมด'},
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, help_text='สถานะการใช้งาน'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='วันที่อัปเดตล่าสุด'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(help_text='ชั้นปีการศึกษา', validators=[django.core.validators.RegexValidator(message='ชั้นปีต้องอยู่ระหว่าง 1-6', regex='^[1-6]$')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='วันที่ลงทะเบียน'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, help_text='ชื่อ นามสกุล และรหัสนักศึกษา', max_length=255, validators=[django.core.validators.RegexValidator(message='ชื่อต้องประกอบด้วยตัวอักษรไทย ภาษาอังกฤษ ตัวเลข วงเล็บ และช่องว่างเท่านั้น', regex='^[ก-๙a-zA-Z\\s\\(\\)0-9]+$'), django.core.validators.MinLengthValidator(3, message='ชื่อต้องมีความยาวอย่างน้อย 3 ตัวอักษร')]),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='MainApp_per_name_6e7136_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['date'], name='MainApp_per_date_9d57a0_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active'], name='MainApp_per_is_acti_3cbab9_idx'),
        ),
    ]
