# Generated by Django 5.2.4 on 2025-07-22 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_person_options_person_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(db_index=True, help_text='อายุ (1-100 ปี)', validators=[django.core.validators.RegexValidator(message='อายุต้องอยู่ระหว่าง 1-100 ปี', regex='^([1-9]|[1-9][0-9]|100)$')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, help_text='ชื่อ นามสกุล และรหัสนักศึกษา', max_length=255, validators=[django.core.validators.RegexValidator(message='ชื่อต้องประกอบด้วยตัวอักษรไทย ภาษาอังกฤษ ตัวเลข วงเล็บ ขีดกลาง จุด ขีดล่าง และช่องว่างเท่านั้น', regex='^[ก-๙a-zA-Z\\s\\(\\)0-9\\-\\.\\_]+$'), django.core.validators.MinLengthValidator(3, message='ชื่อต้องมีความยาวอย่างน้อย 3 ตัวอักษร')]),
        ),
    ]
